function robot = make_robot()
%MAKE_ROBOT Creates the kinematic structure of the robot used in homework 5, problem 1.
%
%   This is a factory function that creates the robot used in the homework.
%
%   Inputs: none
%
%   Output: robot - the robot structure, created using Peter Corke's
%   robotics toolbox
%
%   Author: L. Fichera <lfichera@wpi.edu>
%   Last modified: 4/05/2023

%% Create the manipulator
L1 = 0.360; 
L3 = 0.429; 
L5 = 0.400; 
L7 = 0.126;

robot = SerialLink([Revolute('a', 0, 'd', L1, 'alpha', -pi/2), ...
                    Revolute('a', 0, 'd', 0, 'alpha', pi/2), ...
                    Revolute('a', 0, 'd', L3, 'alpha', pi/2), ...
                    Revolute('a', 0, 'd', 0, 'alpha', -pi/2), ...
                    Revolute('a', 0, 'd', L5, 'alpha', -pi/2), ...
                    Revolute('a', 0, 'd', 0, 'alpha', pi/2), ...
                    Revolute('a', 0, 'd', L7, 'alpha', 0)], ...
                    'name', 'KUKA IIWA 7');

% 
% L1 = 0.2363; 
% L4 = 0.2010; 
% L5 = 0.1593; 
% L6 = 0.1543;
% 
% robot = SerialLink([Revolute('a', 0, 'd', L1, 'alpha', pi/2), ...
%                     Revolute('a', 0, 'd', 0, 'alpha', 0), ...
%                     Revolute('a', 0, 'd', 0, 'alpha', 0), ...
%                     Revolute('a', 0, 'd', L4, 'alpha', pi/2), ...
%                     Revolute('a', 0, 'd', L5, 'alpha', -pi/2), ...
%                     Revolute('a', 0, 'd', L6, 'alpha', 0)], ...
%                     'name', 'UR30');

end